import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Facebook Video Downloader",
  description: "Generated by create next app",
};

export const accordionItems = [
  {
    title: "Is it free or there is limit?",
    content:
      "Its totally free and there is no limit to the number of videos you can download. You can download as many as you want. But you can help us by buying us a coffee.",
  },
  {
    title: "Can I download videos from my Facebook account?",
    content:
      "Yes, you can download videos from your Facebook account. You can also download videos from your friends and family.",
  },
  {
    title: "What if I don’t have a Facebook account?",
    content: "You can still download videos from your friends and family.",
  },
  {
    title: "What if I don't have a computer?",
    content:
      "You can use our web app on your mobile phone. You can download videos from your friends and family.",
  },
  {
    title: "What if the video is private?",
    content:
      "You wont be able to download a private video because its locked by the owner",
  },
];


export const latestNews = [
  {
    title: 'This Facebook Video and Reel Downloader web app is created by Ibrahim Damilola Dhikirullahi',
    color: 'bg-primary'
  },
  {
    title: 'This Facebook Video and Reel Downloader web app is created by Ibrahim Damilola Dhikirullahi',
    color: 'bg-primary-foreground'
  },
  {
    title: 'This Facebook Video and Reel Downloader web app is created by Ibrahim Damilola Dhikirullahi',
    color: 'bg-yellow-500'
  },
  {
    title: 'This Facebook Video and Reel Downloader web app is created by Ibrahim Damilola Dhikirullahi',
    color: 'bg-blue-500'
  },
  {
    title: 'This Facebook Video and Reel Downloader web app is created by Ibrahim Damilola Dhikirullahi',
    color: 'bg-yellow-500'
  },
  {
    title: 'This Facebook Video and Reel Downloader web app is created by Ibrahim Damilola Dhikirullahi',
    color: 'bg-blue-700'
  },
]